package com.example.kaiajourneythroughgrief.dialogues;

import com.example.kaiajourneythroughgrief.DialogueConfig;
import com.example.kaiajourneythroughgrief.DialogueConfig.DialogueLine;
import com.example.kaiajourneythroughgrief.DialogueConfig.DialogueLine.Speaker;

import java.util.Arrays;
import java.util.List;


public class Dialogue2 {

    public static DialogueConfig getConfig() {
        return new DialogueConfig(
                "Dialogue2",
                "/com/example/kaiajourneythroughgrief/assets/dialogueScreen/dialogue2/background.png",
                "",
                0.2,  // Quiet, eerie music
                "Kai",
                "/com/example/kaiajourneythroughgrief/assets/dialogueScreen/dialogue2/left.png",
                "???",
                "/com/example/kaiajourneythroughgrief/assets/dialogueScreen/dialogue2/right.png",
                getDialogueLines()
        );
    }

    private static List<DialogueLine> getDialogueLines() {
        return Arrays.asList(
                new DialogueLine(Speaker.NARRATOR, "KAI wakes up on her back.",
                        "/com/example/kaiajourneythroughgrief/assets/dialogue/43.mp3"),
                new DialogueLine(Speaker.NARRATOR, "Pale ground. Flat. It stretches in every direction—no horizon, just a vast expanse meeting a colorless sky. She lowers her hand, pressing it flat against the surface. It gives slightly, like dry clay.",
                        "/com/example/kaiajourneythroughgrief/assets/dialogue/44.mp3"),
                new DialogueLine(Speaker.NARRATOR, "She sits up, begrudgingly, rubbing the back of her neck.",
                        "/com/example/kaiajourneythroughgrief/assets/dialogue/45.mp3"),
                new DialogueLine(Speaker.NARRATOR, "The sky is empty. No sun. No clouds. The absence of life is the most pressing detail in this domain.",
                        "/com/example/kaiajourneythroughgrief/assets/dialogue/46.mp3"),
                new DialogueLine(Speaker.NARRATOR, "It takes a second for that to settle in.",
                        "/com/example/kaiajourneythroughgrief/assets/dialogue/47.mp3"),
                new DialogueLine(Speaker.NARRATOR, "She opens her mouth. Closes it.",
                        "/com/example/kaiajourneythroughgrief/assets/dialogue/48.mp3"),
                new DialogueLine(Speaker.NARRATOR, "A beat.",
                        "/com/example/kaiajourneythroughgrief/assets/dialogue/49.mp3"),
                new DialogueLine(Speaker.NARRATOR, "She claps her hands once.",
                        "/com/example/kaiajourneythroughgrief/assets/dialogue/50.mp3"),
                new DialogueLine(Speaker.NARRATOR, "The sound arrives a beat later.",
                        "/com/example/kaiajourneythroughgrief/assets/dialogue/51.mp3"),
                new DialogueLine(Speaker.NARRATOR, "She looks down at her hands, turning them over. Palm. Back. Palm. Back.",
                        "/com/example/kaiajourneythroughgrief/assets/dialogue/52.mp3"),
                new DialogueLine(Speaker.NARRATOR, "Nothing.",
                        "/com/example/kaiajourneythroughgrief/assets/dialogue/53.mp3"),
                new DialogueLine(Speaker.LEFT, "Where am I?",
                        "/com/example/kaiajourneythroughgrief/assets/dialogue/54.mp3"),
                new DialogueLine(Speaker.NARRATOR, "Her voice lands flat. No echo. It doesn't travel. It just stops to a halt.",
                        "/com/example/kaiajourneythroughgrief/assets/dialogue/55.mp3"),
                new DialogueLine(Speaker.LEFT, "What is this place?",
                        "/com/example/kaiajourneythroughgrief/assets/dialogue/56.mp3"),
                new DialogueLine(Speaker.NARRATOR, "No answer.",
                        "/com/example/kaiajourneythroughgrief/assets/dialogue/57.mp3"),
                new DialogueLine(Speaker.NARRATOR, "She waits.",
                        "/com/example/kaiajourneythroughgrief/assets/dialogue/58.mp3"),
                new DialogueLine(Speaker.LEFT, "Hello?",
                        "/com/example/kaiajourneythroughgrief/assets/dialogue/59.mp3"),
                new DialogueLine(Speaker.NARRATOR, "Nothing.",
                        "/com/example/kaiajourneythroughgrief/assets/dialogue/60.mp3"),
                new DialogueLine(Speaker.NARRATOR, "Up ahead, KAI sees a body of water—or something that passes for it. She heads toward it, her footsteps making no sound as she steps toward the ocean.",
                        "/com/example/kaiajourneythroughgrief/assets/dialogue/61.mp3"),
                new DialogueLine(Speaker.NARRATOR, "She kneels at the edge, just at the shore, leaning over.",
                        "/com/example/kaiajourneythroughgrief/assets/dialogue/62.mp3"),
                new DialogueLine(Speaker.NARRATOR, "No reflection. No movement. Her face should have been visible the moment she looked over, as well as ripples on the water—anything that would have shown signs of life. It doesn't. Like the sky, it's a vast expanse of grayness.",
                        "/com/example/kaiajourneythroughgrief/assets/dialogue/63.mp3"),
                new DialogueLine(Speaker.NARRATOR, "For a long moment, KAI stares at the surface. She waits.",
                        "/com/example/kaiajourneythroughgrief/assets/dialogue/64.mp3"),
                new DialogueLine(Speaker.NARRATOR, "Nothing changes.",
                        "/com/example/kaiajourneythroughgrief/assets/dialogue/65.mp3"),
                new DialogueLine(Speaker.NARRATOR, "She stands up, turning around. The figures she sees in the distance are a sight to behold—unclear shapes, unmoving like the ocean.",
                        "/com/example/kaiajourneythroughgrief/assets/dialogue/66.mp3"),
                new DialogueLine(Speaker.NARRATOR, "KAI steps forward toward the figures. The ground shifts underneath her feet, as if she were stepping on something not meant to be walked on.",
                        "/com/example/kaiajourneythroughgrief/assets/dialogue/67.mp3"),
                new DialogueLine(Speaker.NARRATOR, "She halts.",
                        "/com/example/kaiajourneythroughgrief/assets/dialogue/68.mp3"),
                new DialogueLine(Speaker.NARRATOR, "The shapes don't move.",
                        "/com/example/kaiajourneythroughgrief/assets/dialogue/69.mp3"),
                new DialogueLine(Speaker.NARRATOR, "On the horizon, five shapes loom ahead. They're far enough that she can't determine their size, yet close enough to see they're glowing. Each shape glows in different colors.",
                        "/com/example/kaiajourneythroughgrief/assets/dialogue/70.mp3"),
                new DialogueLine(Speaker.NARRATOR, "KAI squints.",
                        "/com/example/kaiajourneythroughgrief/assets/dialogue/71.mp3"),
                new DialogueLine(Speaker.NARRATOR, "To the left is a forest, engulfed with a hazy blue light swallowed in fog. The fog hangs around the trees, unmoving—edges blurring into something difficult to perceive, just like everything else KAI has seen so far.",
                        "/com/example/kaiajourneythroughgrief/assets/dialogue/72.mp3"),
                new DialogueLine(Speaker.NARRATOR, "The second is a city, adorned with broken windows and smashed surfaces. The jagged edges of the buildings pulse with a red light.",
                        "/com/example/kaiajourneythroughgrief/assets/dialogue/73.mp3"),
                new DialogueLine(Speaker.NARRATOR, "She looks away, turning slightly.",
                        "/com/example/kaiajourneythroughgrief/assets/dialogue/74.mp3"),
                new DialogueLine(Speaker.NARRATOR, "The third structure doesn't seem to hold any visible shape—a temple with doors surrounding each surface. The walls, ground, and roof are closed, shifting, too deep to follow along. It emits a yellow light through the cracks.",
                        "/com/example/kaiajourneythroughgrief/assets/dialogue/75.mp3"),
                new DialogueLine(Speaker.NARRATOR, "Then, an ocean, reminiscent of the body of water KAI approached just moments ago—still, vast, dark. Although she already stands in one, the difference is that the distant ocean seems deeper, stiller, as the colors bleed into hues of blue-violet rather than gray. Indigo.",
                        "/com/example/kaiajourneythroughgrief/assets/dialogue/76.mp3"),
                new DialogueLine(Speaker.NARRATOR, "And, finally, further out, there's something that doesn't pull at her or tread on her skin. It turns out to be a garden. Flowers spill freely, unmoving in the wind. The light is a soft gold, the same hue as dawn's light. More than anything, it appears distant in a different way.",
                        "/com/example/kaiajourneythroughgrief/assets/dialogue/77.mp3"),
                new DialogueLine(Speaker.NARRATOR, "KAI stands looking over them all.",
                        "/com/example/kaiajourneythroughgrief/assets/dialogue/78.mp3"),
                new DialogueLine(Speaker.NARRATOR, "Then, just as KAI was about to embark on a long voyage to the forest, she hears a voice.",
                        "/com/example/kaiajourneythroughgrief/assets/dialogue/79.mp3"),
                new DialogueLine(Speaker.RIGHT, "You need to move.",
                        "/com/example/kaiajourneythroughgrief/assets/dialogue/80.mp3"),
                new DialogueLine(Speaker.NARRATOR, "KAI looks around to search for the origin of the sound, but to no avail.",
                        "/com/example/kaiajourneythroughgrief/assets/dialogue/81.mp3"),
                new DialogueLine(Speaker.NARRATOR, "She turns, giving the colorless sky and the gray ocean a once-over before she halts.",
                        "/com/example/kaiajourneythroughgrief/assets/dialogue/82.mp3"),
                new DialogueLine(Speaker.LEFT, "Where?",
                        "/com/example/kaiajourneythroughgrief/assets/dialogue/83.mp3"),
                new DialogueLine(Speaker.NARRATOR, "A beat of silence.",
                        "/com/example/kaiajourneythroughgrief/assets/dialogue/84.mp3"),
                new DialogueLine(Speaker.RIGHT, "Through them.",
                        "/com/example/kaiajourneythroughgrief/assets/dialogue/85.mp3"),
                new DialogueLine(Speaker.NARRATOR, "A gust of wind occurs, passing through her before stopping to a halt in the forest adorned in blue light.",
                        "/com/example/kaiajourneythroughgrief/assets/dialogue/86.mp3"),
                new DialogueLine(Speaker.NARRATOR, "It sweeps across the landmarks—from blue, to red, to yellow, to indigo, then into gold.",
                        "/com/example/kaiajourneythroughgrief/assets/dialogue/87.mp3"),
                new DialogueLine(Speaker.LEFT, "Which one? What do you mean by \"through them\"?",
                        "/com/example/kaiajourneythroughgrief/assets/dialogue/88.mp3"),
                new DialogueLine(Speaker.NARRATOR, "Only silence answers her.",
                        "/com/example/kaiajourneythroughgrief/assets/dialogue/89.mp3"),
                new DialogueLine(Speaker.NARRATOR, "She stares back at the shapes—five different surfaces with differently colored lights engulfing them.",
                        "/com/example/kaiajourneythroughgrief/assets/dialogue/90.mp3"),
                new DialogueLine(Speaker.RIGHT, "You must pass through every door that stands before you. Until each has claimed what it asks of you, there will be no return to the surface.",
                        "/com/example/kaiajourneythroughgrief/assets/dialogue/91.mp3"),
                new DialogueLine(Speaker.NARRATOR, "You stand at a crossroads of everything you have buried—everything you overlooked despite the weight of it pressing on your shoulders.",
                        "/com/example/kaiajourneythroughgrief/assets/dialogue/92.mp3"),
                new DialogueLine(Speaker.NARRATOR, "You have told yourself to put it aside, to deal with it later, even if it hinders every step forward. You are suspended between dreaming and waking.",
                        "/com/example/kaiajourneythroughgrief/assets/dialogue/93.mp3"),
                new DialogueLine(Speaker.NARRATOR, "You are not asleep, yet not fully awake. In between. The only way through is forward.",
                        "/com/example/kaiajourneythroughgrief/assets/dialogue/94.mp3"),
                new DialogueLine(Speaker.NARRATOR, "A beat passes.",
                        "/com/example/kaiajourneythroughgrief/assets/dialogue/95.mp3"),
                new DialogueLine(Speaker.NARRATOR, "KAI looks over the shapes—the forest wrapped in blue fog, the destroyed city pulsing red, the temple bathed in yellow, the ocean dark as indigo, and the garden soft under gold.",
                        "/com/example/kaiajourneythroughgrief/assets/dialogue/96.mp3"),
                new DialogueLine(Speaker.LEFT, "Then what am I supposed to do?",
                        "/com/example/kaiajourneythroughgrief/assets/dialogue/97.mp3"),
                new DialogueLine(Speaker.RIGHT, "Walk until one pulls you into it. Walk through the room, then to the succeeding door, until all five are behind you.",
                        "/com/example/kaiajourneythroughgrief/assets/dialogue/98.mp3"),
                new DialogueLine(Speaker.LEFT, "And then?",
                        "/com/example/kaiajourneythroughgrief/assets/dialogue/99.mp3"),
                new DialogueLine(Speaker.RIGHT, "Then, you remember what you came here to forget.",
                        "/com/example/kaiajourneythroughgrief/assets/dialogue/100.mp3")
        );
    }
}